# Host and port of the app to run on.
app:
  host: !ENV ${APP_HOST}
  port: !ENV ${APP_PORT}

# MongoDB's authentication credentials.
database:
  username: !ENV ${MONGO_USERNAME}
  password: !ENV ${MONGO_PASSWORD}
  hostname: !ENV ${MONGO_HOSTNAME}
  port: !ENV ${MONGO_PORT}
  database_name: !ENV ${MONGO_DATABASE_NAME}

# Secret key for JWT authentication.
jwt_secret_key: !ENV ${JWT_SECRET_KEY}

# Length of the randomly generated name for files.
random_name: 10

# WEBP transcode parameters.
webp:
  lossless: True

  # If lossy, 0 gives the smallest size and 100 the largest.
  # If lossless, this is the amount of effort put into the compression -
  # 0 is the fastest, but gives larger files compared to the slowest, but best, 100.
  quality: 26

  # Quality/speed trade-off (0=fast, 6=slower-better).
  method: 1

# Whitelisted MIME types.
mime_type:
  whitelisted: ["audio", "video", "image"]
